# INFURA, parity, geth, etc.
# Note: must be a secure websockets url (wss://)
provider_url = "wss://mainnet.infura.io/ws/v3/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# INFURA, parity, geth, etc.
# Note: must be HTTPS url (https://)
provider_url_https = "https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# ip and port to bind
# examples:
#listen = "127.0.0.1:3333"
#listen = "0.0.0.0:8000"
listen = "0.0.0.0:3333"

# if set, force sending of mining params to all clients once every
# <n> seconds, even if mining parameters haven't actually changed.
# (this is to help mining programmers during development and testing.)
# example, send every 10 seconds:
#force_send = 10
